version: "3"
services:
  python:
    build: .

  web:
    image: notflix_python:latest
    ports:
     - 5000:5000
    volumes:
     - ./src:/src
    working_dir: /src
    environment:
      PYTHONPATH: /src
    env_file:
      - db-credentials.env
    links:
      - api
    command: ["python", "web/wsgi.py"]

  api:
    image: notflix_python:latest
    ports:
      - 5001:5000
    volumes:
      - ./src:/src
    working_dir: /src
    environment:
      PYTHONPATH: /src
    env_file:
      - db-credentials.env
    links:
      - postgres
      - redis
    command: ["python", "api/wsgi.py"]

  redis:
    image: redis:alpine
    volumes:
      - ./src/data/mount/redis:/data

  postgres:
    image: postgres:latest
    env_file:
      - db-credentials.env
    volumes:
      - ./src/data/mount/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    links:
      - adminer

  adminer:
    image: adminer
    ports:
      - 8080:8080
