version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circleci-test
          REDIS_HOST: localhost
          POSTGRES_HOST: localhost
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circleci-test
      - image: circleci/redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests;

      - store_artifacts:
          path: test-reports
          destination: test-reports
